### ISSUE TITLE
Standardize on "disconnected" terminology for OpenShift (possibly beyond)

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#187] opened 2022-06-13 15:59 UTC
In the OpenShift docs, we have used both "disconnected" and "in a restricted network" to describe clusters that have some degree of being separated from the public internet access.

Per OpenShift SMEs, they prefer the term "disconnected" because that's the term they've found our customers are using to find information on it.

We can consider standardizing on this as an OpenShift-specific term, but I'd also like to see what other products are using as their terminology for these situations. To see if it can be recommended more widely across Red Hat.

**Comment by bergerhoffer** [comment] 2022-06-13 16:00
Updating per the thread in the CCS Style Council gchat room that Ansible uses "disconnected", and RHACS uses "offline mode".

**Comment by mnsteven** [comment] 2022-06-13 16:21
It's not really part of HA cluster configuration and administration to talk about whether the cluster is disconnected from the Internet -- the cluster as a whole is on a private network and cluster communication takes place among the nodes of the cluster. An individual cluster resource running on a particular node might be connected to the Internet (and likely is), and if that goes down (in which case the resource is described as being offline) the service that resource was providing moves to a different cluster node, but that doesn't mean the cluster is not connected to the Internet.  In fact, the whole point of an HA cluster is so that it remains connected to the Internet even if something stops working on a particular node.

But within that context, as noted, when a specific node in a cluster (or a cluster resource, which is a specific-to-HA term)  cannot be reached it is noted as being "offline".   I did find one place where "disconnected" is used to describe an offline resource. What's more common is to note that cluster services have stopped (or that the administrator has stopped cluster services) on a node, which isn't quite the same thing as being offline.

For what that's worth -- I'm not sure it's what the rest of this thread is referencing.

**Comment by pwright** [comment] 2022-06-13 17:08
AMQ interconnect uses 'Restricted Environment' (later defined as an environment which has no or limited internet access)

**Comment by porueesq** [comment] 2022-06-17 14:10
@redhat-documentation/ccs-style-council So far, we have these terms:

- disconnected
- restricted network
- offline mode
- air-gapped environment (seen in other documentation instances)

As per this comment (https://github.com/redhat-documentation/supplementary-style-guide/issues/187#issuecomment-1154124173), looks like it's important to distinguish between a resource that has no Internet access  and a resource that stops providing services due to disconnection.

What do you think?

**Comment by mnsteven** [comment] 2022-06-21 15:07
As  per Comment #187. which is mine, it seems to be an issue that affects only the HA cluster documentation.  In that case the issue is that for HA cluster the important thing is is not that a resource is disconnected from the internet but that a resource has moved from one cluster node to another -- which could happen for a variety of reasons, a disconnect from the internet being only one of them (and is only mentioned once throughout the entire corpus of HA documentation). If it happens to be a resource that connects to the internet, then a disconnect will cause that to happen.  But it could also happen if some other aspect of the resource is failing, which may have nothing to do with internet connection.  Much more commonly, however, the issue is that the node itself on which the resource is running cannot be reached by the other nodes in the cluster, so the terminology question is how to refer to the node that can't be reached.  That's where the documentation most commonly refers to that node as being offline, but it's not offline from the internet it's offline from the private network.

So I think the terminology issue is simpler than the question in the previous comment.  There are two situations to describe in the HA cluster documentation:

- The so-far-unique one where a single resource is disconnected from the internet, and in that case the documentation currently uses the term "disconnected".  That came from the main SME/developer, and the documentation he provided me to explain a context.  The term in context was clear enough to me that I never gave it a second thought when using it, and it seems to be consistent with how that terms is used elsewhere (based on this discussion).

- The much more common situation where a node in a cluster (where the nodes are communicating with each other through a private network and continually checking each other's health) cannot be reached by the other node or nodes in a cluster.  That's the situation where until now the documentation refers to the node that can't be reached as being "offline" (not in "offline mode").  In this case I don't think "disconnected" describes the situation -- because it's not a reference to being disconnected from the internet.  As I say, I'm not even sure this is the same situation that is being discussed here, but it seemed worth bringing up.

**Comment by bergerhoffer** [comment] 2022-06-28 19:05
Updating with some more feedback/quotes on this subject from the CCS gchat room:

* "The programs I've worked on have used "disconnected." I've only heard "air-gapped" between folks internally." [ahoffer add: this one was for Ansible and Satellite]
* "I think "air-gapped" mostly refers to offline backups"
* "I am working on an Ansible document for offline installation and we are using 'disconnected' as the standard verbiage rather than 'air-gapped.'"
* "In my past life I used restricted a bit, YMMV"
* "In ODF documents, we have used 'disconnected' (also, have seen the use of 'air-gapped' in a BZ raised by SA)."
* "Disconnected usually, airgapped is used more colloquially" [ahoffer add: this one was for OCS/ODF + other storage products]

**Comment by bergerhoffer** [comment] 2022-08-08 17:17
After further discussion, this is likely a difficult term to try to standardize on across products. For now, will add "disconnected" as an OpenShift-specific term. We can always reopen if we think it's worth trying to do a wider reach/standardization.

**Comment by bburt-rh** [comment] 2022-10-05 20:01
@bergerhoffer Can we close this issue? Thanks!

**Comment by bergerhoffer** [comment] 2022-10-05 21:34
Sorry @bburt-rh I haven't merged the PR yet, so probably shouldn't close it yet. I'm close to getting SME ack on the OpenShift PR, so as soon as I get that, I'll come in and wrap this one up.

**Closed** 2022-12-13 17:48 UTC
Labels: Glossary entry
