### ISSUE TITLE
Assess use of quotations and italics in the Red Hat Supplementary Style Guide (RHSSG)

### ISSUE THREAD

**Issue by dfitzmau** [redhat-documentation/supplementary-style-guide#173] opened 2022-04-14 08:27 UTC
The IBM Style Guide provides specific guidance around the use of quotes and italics when producing documentation. See the _Highlighting by element_ section in the IBM Style Guide. Other notable sections include:

- Code and command examples
- Quotation marks
- Single quotation marks
- Emphasis

The RHSSG shows some inconsistency with the use of quotes and italics when compared to the recommended practice in the IBM SG. This is especially evident for certain words and phrases in the RHSSG.

The purpose of this issue is to clarify the correct highlighting syntax to use for words and phrases in the RHSSG. Perhaps document guidance for the correct highlighting to use, and correct existing highlighting used in the guide.

**Comment by bergerhoffer** [comment] 2022-04-14 13:14
@dfitzmau I know we discussed this in other PRs, but can you provide some specific examples from the SSG that are inconsistent, so that we can review each situation to see whether quotes or italics is appropriate for them?

**Comment by dfitzmau** [comment] 2022-04-19 08:44
Sure:

Example 1: 

> load balancing: "Load balancing" distributes processing and communications activity evenly across a computer network so that no single device is overwhelmed. 

Example 2:

> Red Hat JBoss BRMS : "Red Hat JBoss BRMS" is a comprehensive platform for business rules management, business resource optimization, and complex event processing (CEP).

Example 3:

> xts subsystem: The "xts" subsystem is used to configure settings for coordinating Web services in a transaction.

**Comment by bergerhoffer** [comment] 2022-04-25 17:18
@dfitzmau thanks, that helps!

I feel like we have two situations to determine in the SSG, and I'm not sure if they'll be the same or different:

1. Defining the term, like in your above examples, such as:
>  "Load balancing" distributes processing and...

2. Actually giving guidance on exactly what to write

> Use "distinguished name" on the first usage and then the abbreviation "DN" subsequently.

My first thought would be to italicize the term when we're introducing its definition. And then when we're actually talking about how to write or not write it, to use quotes.

For example:

> _Comma-separated values_ are a set of values in which each value is separated by a comma. Spell out "comma-separated values" on first use; use "CSV" thereafter.

Looking at the ISG, their word usage doesn't go into defining the terms, only describing how to use it in text, and they use quotes. They also actually recommend using fragments instead of full sentences, which would resolve our issue here, but that would be a lot of work to redo so I doubt we'd want to do that.

Otherwise, the closest thing I can see in the ISG is this:

> Words and phrases that are defined or explained

With a recommended highlighting style of italic.

So I'm taking that to mean what I proposed above, (italics when defining the term, double quotes when telling users what to write or not write), but I'd like to hear what others think.

**Comment by mportman12** [comment] 2022-04-25 20:07
@bergerhoffer Per the ISG's guidance, I agree that italicizing the first use of the defined term is correct.

**Comment by dfitzmau** [comment] 2022-04-26 08:04
+1 @bergerhoffer . I agree with your use cases for italics and quotes

How many votes/approvals do we need to get to convert this issue into a PR?

**Comment by bergerhoffer** [comment] 2022-04-26 19:44
@dfitzmau We have this on the agenda for tomorrow's SSG meeting, so we can see what others think. Since this would be a bit of a task to do a sweep, let's make sure that more than our normal 3 approvals are good with it before we start implementing anything.

**Comment by dfitzmau** [comment] 2022-04-27 07:42
Thanks, @bergerhoffer .

**Comment by dfitzmau** [comment] 2022-05-05 12:55
Hi @bergerhoffer .

Just checking in with you on the outcome from this issue in the SSG meeting. Any decision made?

**Comment by bergerhoffer** [comment] 2022-05-05 13:53
There was mostly agreement on using italics for defining terms and using quotes later when telling people what to write or not write. But we didn't come to a complete decision on moving forward with it (kind of ran out of time in the mtg).

So before moving forward with doing a sweep, I think we want some more confirmed +1's (or objections) in this issue.

@redhat-documentation/ccs-style-council PTAL and let us know if you're okay with the following approach:

- Italicize the term when we're introducing its definition. And then when we're actually talking about how to write or not write it, to use quotes.

  For example:

  > _Comma-separated values_ are a set of values in which each value is separated by a comma. Spell out "comma-separated values" on first use; use "CSV" thereafter.

**Comment by mportman12** [comment] 2022-05-05 14:09
+1 for this approach, but recommend waiting on updating the SSG glossary until after the product-specific reorg is finished.

**Comment by dfitzmau** [comment] 2022-05-05 14:26
Thanks, @bergerhoffer . I like your suggestions, so I'll +1 to these also. We'll need to define a section for this in the SSG?

**Comment by dfitzmau** [comment] 2022-05-05 14:47
OK, thanks, @bergerhoffer . I just wonder if deviations will occur again in the future.

**Comment by Srivaralakshmi** [comment] 2022-05-05 14:58
+1 to the suggestions of @bergerhoffer and @mportman12 for now.

**Comment by ndeevy** [comment] 2022-05-05 15:22
+1 to @bergerhoffer's suggestion. Logical

**Comment by porueesq** [comment] 2022-05-05 15:44
According to the ISG:
![image](https://user-images.githubusercontent.com/43811485/166961003-2fce1b8c-cf5a-4e21-b6d6-48b8fd89af46.png)

Hence, the example provided above should be:
> Comma-separated values: Set of values in which each value is separated by a comma. Spell out "comma-separated values" on first use; use "CSV" thereafter.

I think that using only quotes is simpler.

**Comment by dfitzmau** [comment] 2022-08-31 13:51
Thanks, @bergerhoffer .

I created the following PR: https://github.com/redhat-documentation/supplementary-style-guide/pull/215

**Comment by dfitzmau** [comment] 2022-09-02 09:09
Updated glossary entries for italics and quotes us is captured through the following PRs:

- A-F: https://github.com/redhat-documentation/supplementary-style-guide/pull/217

**Comment by bergerhoffer** [comment] 2022-09-27 17:52
@redhat-documentation/ccs-style-council Can we get a few people to help work on these updates for a handful of letters between G-Z?

**Comment by bburt-rh** [comment] 2022-10-05 20:00
@bergerhoffer I can start in on G and see how far I get over the next week or so.

**Comment by dfitzmau** [comment] 2022-10-06 08:31
> @bergerhoffer I can start in on G and see how far I get over the next week or so.

Thanks so much for this, @bburt-rh ! 

I'm backed up with docs work on 3 products until mid-Novemeber. I do plan to continue on any remaining alphabetic listings for these updates.

**Comment by bergerhoffer** [comment] 2022-12-06 19:05
A-F and J-Z are done.

The last letters we need to do are G-I.

**Comment by bburt-rh** [comment] 2023-01-18 20:50
@bergerhoffer It's on my to-do list to get a PR created for this next week. (Sorry - but this one fell by the wayside!)

**Comment by bergerhoffer** [comment] 2023-02-08 21:37
Closing this issue, since the last PR (#283) for this just merged!

**Closed by bergerhoffer** 2023-02-08 21:37 UTC
Labels: General update
